// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW67yLAndrPvxOwUZMInpOJAzIw0sA5g8',
    appId: '1:871337335864:web:42b76f0c8cb05b237c5acd',
    messagingSenderId: '871337335864',
    projectId: 'sunozara-54b5a',
    authDomain: 'sunozara-54b5a.firebaseapp.com',
    storageBucket: 'sunozara-54b5a.appspot.com',
    measurementId: 'G-LCCSK3VK6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4fXVN2jwcaLpCrFk4uatFs9I3Sqi3VdM',
    appId: '1:871337335864:android:3d2892bc72983cd87c5acd',
    messagingSenderId: '871337335864',
    projectId: 'sunozara-54b5a',
    storageBucket: 'sunozara-54b5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOJqMlWQBeBRcuUyVEe9exPOpDfaJUFzg',
    appId: '1:871337335864:ios:32fcaf7272757a5a7c5acd',
    messagingSenderId: '871337335864',
    projectId: 'sunozara-54b5a',
    storageBucket: 'sunozara-54b5a.appspot.com',
    androidClientId: '871337335864-tspg0bgio8pp6nkk3gri8qp60anqfaj1.apps.googleusercontent.com',
    iosClientId: '871337335864-og7geq3qbiga0p65p7vsol02jh4l3ni4.apps.googleusercontent.com',
    iosBundleId: 'com.sunozara.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOJqMlWQBeBRcuUyVEe9exPOpDfaJUFzg',
    appId: '1:871337335864:ios:32fcaf7272757a5a7c5acd',
    messagingSenderId: '871337335864',
    projectId: 'sunozara-54b5a',
    storageBucket: 'sunozara-54b5a.appspot.com',
    androidClientId: '871337335864-tspg0bgio8pp6nkk3gri8qp60anqfaj1.apps.googleusercontent.com',
    iosClientId: '871337335864-og7geq3qbiga0p65p7vsol02jh4l3ni4.apps.googleusercontent.com',
    iosBundleId: 'com.sunozara.user',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW67yLAndrPvxOwUZMInpOJAzIw0sA5g8',
    appId: '1:871337335864:web:7bc565a7abb7d1227c5acd',
    messagingSenderId: '871337335864',
    projectId: 'sunozara-54b5a',
    authDomain: 'sunozara-54b5a.firebaseapp.com',
    storageBucket: 'sunozara-54b5a.appspot.com',
    measurementId: 'G-W7ZVQ5CSFM',
  );

}